### PR TITLE
Add wrap_attributes and wrap_indent config parameters for HTML

### PR DESCRIPTION
**Pull request by sankargorthi**
This will put attributes on new lines if configured

#### input
-------
```html
<div    {{something}} attr1="123" data-attr2="hello    t here" {{#test}}disabled {{/test}}

>
This is some content    </div>
<div oneattr="one">
    Some content
            </div>
```

#### `config.json`
```json
{
    "wrap_attributes": true,
    "wrap_indent": 8,
    "wrap_line_length": 144
}
```

#### output
```html
<div {{something}}
        attr1="123"
        data-attr2="hello    t here"
        {{#test}}disabled
        {{/test}}>
    This is some content</div>
<div oneattr="one">
    Some content
</div>

```

### CODE REVIEW

**Comment by bitwiseman** [comment]
Just waiting for your changes.

**Comment by sankargorthi** [comment]
I'm not getting enough time to work on this. Would someone else like to collaborate and contribute to this?

**Comment by filipesilva** [comment]
This is driving me nuts on my project. How can I help?

**Comment by bitwiseman** [comment]
Pickup the changes, merge to resolve the conflicts, and finish the TODO's.

**Comment by filipesilva** [comment]
Done, I think. If I did something obviously bad please tell me so I can fix it.

**Pull request merged**
