### PR TITLE
Fixing https://github.com/beautify-web/js-beautify/issues/1658

### PR DESCRIPTION
**Pull request by asteinha**
Fixing https://github.com/beautify-web/js-beautify/issues/1658
First we need to verify whether there is another input before matching its value.

### CODE REVIEW

**Comment by bitwiseman** [comment]
@asteinha
Excellent, thanks.  Can you add a test for this?

**Comment by asteinha** [comment]
Done.

**Comment by bitwiseman** [comment]
@asteinha Please modify the data file `test/data/javascript/tests.js` and run the build to generate the tests.

**Comment by asteinha** [comment]
Done

**Pull request merged**
