### PR TITLE
Obey `wrap_attributes_indent_size` after auto wrap

### PR DESCRIPTION
**Pull request by robrez**
Fixes https://github.com/beautify-web/js-beautify/issues/640

### CODE REVIEW

**Comment by robrez** [comment]
Hmm I _think_ the tests might be wrong. I didn't think to modify them...

**Comment by bitwiseman** [comment]
Feel free to modify them.  That is how I can see the effects of your changes.

**Comment by bitwiseman** [comment]
@robrez - Ping?

**Comment by robrez** [comment]
Ooops! I'll try and get back to you today, @bitwiseman !

**Comment by robrez** [comment]
@bitwiseman I pushed an additional change to `beautify-html.js` and changed a line in `test/data/html/tests.js`

**Comment by bitwiseman** [comment]
@robrez - I've updated the test framework per your suggestion.

I see you modified the tests to reproduce the current behavior with your new settings.  Great!
Now please add tests showing the new behavior and we'll be good to go.

**Pull request merged**
