### PR TITLE
Fix for issue 1153: Newlines are inserted between anchor tags around images

### PR DESCRIPTION
**Pull request by jhaines**
The tag variable in this function is presently an array, returned from the match called on the next tag.

Since the Utils.in_array function called on the list of unformatted tags requires a string, we need the second value of the array, which returns the subgroup with the tag name, such as "img" in "\.

### CODE REVIEW

**Comment by jhaines** [comment]
I've added some more tests.  Also one of the previous tests had a typo of "fragement" instead of "fragment".  I don't think it was causing issues, but I've fixed it regardless.

**Comment by TheSpyder** [comment]
Github hasn't linked them due to the lack of a # in the title, but this fixes #1153

**Comment by bitwiseman** [comment]
@jhaines - thanks, I'm going to wait a few more days on to merge this, but it looks good to me.

**Comment by TheSpyder** [comment]
Has enough time passed? This triggers a minor bug in our editor and it would be nice to have an updated JS Beautifier release to fix it :)

**Pull request merged**
