### PR TITLE
'<?php ?>' as a single html tag.

### PR DESCRIPTION
**Pull request by yustnip**
Added '?php' to the list of single tags. It will allow to get a pretty code when HTML contains constructions like <?php echo $var; ?>.

### CODE REVIEW

**Comment by bitwiseman** [comment]
Need some added tests before we can merge this.

**Comment by Oxicode** [comment]
+1

**Comment by bitwiseman** [comment]
@Oxicode - Thanks for the vote!  it looks like @yustnip is not responding, would you like to add tests that show this working?

**Comment by yustnip** [comment]
I don't know how to do it right. :) I can provide screenshots:
https://yadi.sk/i/PMRg8KFLkrsmg
https://yadi.sk/i/GoaJqyBckrsnD

**Comment by bitwiseman** [comment]
Sorry, screenshots don't help at all.  Need to have repeatable tests. 
Make changes to https://github.com/beautify-web/js-beautify/blob/master/test/data/html.js 
Then run `make testj`.  That will generate tests based on the data you added, and then will run them.

**Comment by bitwiseman** [comment]
Looks like this would fix  #826.

**Pull request closed without merging**
