### PR TITLE
Add consistent_comment_rule option for CSS

### PR DESCRIPTION
**Pull request by leoliu1313**

### CODE REVIEW

**Comment by leoliu1313** [comment]
consistent_comment_rule option is false by default.
This change is not only in javascript, but also in python codes and regressions.
This shall be an option to be used for brackets-beautify project as an extension for Brackets.
https://github.com/leoliu1313/brackets-beautify
https://github.com/drewhamlett/brackets-beautify
http://brackets.io/

**Comment by leoliu1313** [comment]
Travis CI is clean now.
https://travis-ci.org/beautify-web/js-beautify/builds/60225208
https://travis-ci.org/leoliu1313/js-beautify

Travis CI error is fixed by uploading the output files generated by Makefile.

**Comment by bitwiseman** [comment]
Excellent.  Yes, checking in the outputs in this case is correct. I'll review this shortly.

**Comment by leoliu1313** [comment]
Thank you!

**Comment by leoliu1313** [comment]
This shall fix the folloing issues.
https://github.com/beautify-web/js-beautify/issues/531
https://github.com/beautify-web/js-beautify/issues/609
https://github.com/beautify-web/js-beautify/issues/645

**Comment by loganknecht** [comment]
Hi there, I'm interested to know if this has been reviewed and if its integration is planned.

Specifically because I'm looking for a solution to fix the issue I'm encountering with #609.

**Comment by bitwiseman** [comment]
Reviewed now.  I'm not convinced this is the right path for this.  This doesn't so much fix the issues you listed as create a different set of issues.  If we're going to make this change it shouldn't be an option, it should be the standard behavior.   

Having "consistent" behavior is good, but this implementation produces worse outputs in some cases.

**Comment by bitwiseman** [comment]
@loganknecht - #609 fixed.  Will be in next release coming within the week.

**Pull request closed without merging**
