### PR TITLE
Bugfix for #722

### PR DESCRIPTION
**Pull request by corgrath**
Hey. This is a pull request to solve issue https://github.com/beautify-web/js-beautify/issues/722

I know there is a setup you need to do, that includes Python, but since I have no Python experience at all, I had problems setting the test environment up. But I saw that Travis-ci, so hopefully that can help with testing. If not, is there a chance any main developers can help verify that this fix doesn't break anything?

### CODE REVIEW

**Comment by corgrath** [comment]
The problem is that I haven't added any new test cases to ensure this change will preserve. Is this something you can help me with?

This could be a test case:
```
.mixin( {
background:
red;
}
)
;
```
Should become
```
.mixin( {
    background: red;
} );
```

**Comment by bitwiseman** [comment]
Please look at https://github.com/beautify-web/js-beautify/blob/master/test/data/css.js.  Add you test using that json, then run make.  This will generate tests for python and javascript.

**Comment by corgrath** [comment]
I am closing this.

I cannot build the project, as I am getting problems running make in windows.

Perhaps someone else in the future has the time to create the necessary tests.

**Comment by bitwiseman** [comment]
@corgrath - What problems are you getting building in windows?

**Pull request closed without merging**
