### PR TITLE
Format yield* the same as function*

### LINKED ISSUE #920: Do not put a space within `yield*` generator functions.
This is basically the same as #428, but for the `yield` statement.

The beautifier is changing `yield* myFunc();` to `yield * myFunc();`, which then does not pass our linting rules (http://eslint.org/docs/rules/yield-star-spacing). Ideally, this should not be changed at all.

### PR DESCRIPTION
**Pull request by jgeurts**
Fixes #920 to have `yield*` formatting follow `function*` formatting

### CODE REVIEW

**Comment by jgeurts** [comment]
I'm not sure how to have the checks complete properly for this - if there's a way to do that, please let me know!

**Comment by bitwiseman** [comment]
Hello, I'm sorry for the delay.  I've had no time to review changes or to fix the issue with the CI tools. Please be patient.

**Comment by jgeurts** [comment]
Awesome, just wanted to make sure I wasn't missing anything. If I can do anything in the mean time, please let me know.

**Comment by Kitanotori** [comment]
Would also be happy if this was fixed. Recently started using [redux-saga](https://github.com/yelouafi/redux-saga) for async processing, and it is heavily dependant on generator functions.

**Comment by bitwiseman** [comment]
@jgeurts - Thanks, I took your change and made some tweaks and added python implementation.

**Comment by jgeurts** [comment]
Great, thanks!

**Pull request closed without merging**
