### PR TITLE
bug: fix psf/black package version

### PR DESCRIPTION
**Pull request by mhnaeem**
# Description
The latest release of black has introduced breaking changes which affect the ci pipeline and python test. Specify a version for download until that can be fixed.

Fixes Issue: 
#1995

### CODE REVIEW

**Comment by bitwiseman** [comment]
Instead of locking the version, perhaps you could run the new version and apply the changes?

**Review by bitwiseman — CHANGES_REQUESTED** [review]
If we can avoid locking to an old version it would be better.

**Comment by mhnaeem** [comment]
> Instead of locking the version, perhaps you could run the new version and apply the changes?

@bitwiseman I am not 100% familiar with the usage of that tool but according to their release notes for the [v22.1.0](https://github.com/psf/black/blob/main/CHANGES.md#2210) they removed entire support for Python 2. So the fix here would be to use an alternative package or stop running Python2 by removing `'py27'` from the target versions in `python/pyproject.toml`.

See link for more info: https://github.com/psf/black/pull/2740

**Comment by bitwiseman** [comment]
It is probably time for this tool to remove python 2 support. Would you be willing to make that change?

**Comment by mhnaeem** [comment]
> Would you be willing to make that change?

@bitwiseman I am not entirely sure what is required to make that possible. I will be happy to contribute some time if there is a well defined list of issues or things that need done.

**Review by bitwiseman — APPROVED** [review]

**Pull request merged**
