### PR TITLE
Fixed whitespace detection issue with tests

### LINKED ISSUE #1496: ReferenceError: token is not defined
# Description
I am getting the error message `ReferenceError: token is not defined` while running this on text that has [NO-BREAK-SPACE character](https://www.fileformat.info/info/unicode/char/00a0/index.htm) in the content.

# Input
The code looked like this before beautification:
```
<p>hello world</p>
```

# Expected Output
The code should have looked like this after beautification:
```
<p>hello world</p>
```

# Actual Output
The  code actually looked like this after beautification:
```
ReferenceError: token is not defined
    at Beautifier.beautify (/Users/siva/.nvm/versions/node/v8.11.3/lib/node_modules/js-beautify/js/src/html/beautifier.js:372:29)
    at style_html (/Users/siva/.nvm/versions/node/v8.11.3/lib/node_modules/js-beautify/js/src/html/index.js:33:21)
    at Function.style_html (/Users/siva/.nvm/versions/node/v8.11.3/lib/node_modules/js-beautify/js/src/index.js:36:10)
    at makePretty (/Users/siva/.nvm/versions/node/v8.11.3/lib/node_modules/js-beautify/js/lib/cli.js:448:36)
    at Object.processInputSync (/Users/siva/.nvm/versions/node/v8.11.3/lib/node_modules/js-beautify/js/lib/cli.js:442:5)
    at Array.forEach (<anonymous>)
    at Object.exports.interpret (/Users/siva/.nvm/versions/node/v8.11.3/lib/node_modules/js-beautify/js/lib/cli.js:305:15)
    at Object.<anonymous> (/Users/siva/.nvm/versions/node/v8.11.3/lib/node_modules/js-beautify/js/bin/js-beautify.js:4:5)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
```

js-beautify version - 1.8.0-rc12

### PR DESCRIPTION
**Pull request by MacKLess**
Fixes #1496
@astronomersiva this converts the &nbsp character into a space. I think this is a decent fix, because people generally should be using `&nbsp;` in html. Let me know if you disagree.

### CODE REVIEW

**Comment by Hirse** [comment]
In HTML, I could see an argument for keeping a &nbsp character or changing it to `&nbsp;` as it can technically change the layout, even though it is certainly bad style.

**Comment by garretwilson** [comment]
> In HTML, I could see an argument for keeping a &nbsp character or changing it to `&nbsp;`…

I don't know the details of this pull request; I'm only commenting because I'm participating in #1495.

* There is nothing wrong with the `U+00A0`. It is necessary in many instances, e.g. to prevent icon+menu items from wrapping. _Please never, ever change `U+00A0` to a normal space character!_ This is corrupting content, and is the worse thing you could do.
* Please do not change `U+00A0` to `&nbsp;`. While this named character reference is guaranteed to be recognized as HTML, if the source file is XML-based (e.g. XHTML) then it will break parsing because in XML all entities other than the predefined entities must be defined in an internal or external XML DTD.

So please no workarounds that involve mucking with the content. **_Leave the content as it is!!!_** A non-breaking space should be formatting according to the semantics: i.e. don't wrap on a non-breaking space.

**Comment by bitwiseman** [comment]
@garretwilson 
Okay, so being strict and accurate with the whitespace detection in HTML matters.  Good to know.  Great user-feedback as always.   

@MacKLess  It looks like the HTML tokenizer will need to specifically only match "space characters" 
as noted in https://www.w3.org/TR/html5/infrastructure.html#space-characters when separating words. All other characters will need to be treated as text.

**Comment by garretwilson** [comment]
> It looks like the HTML tokenizer will need to specifically only match "space characters" …

I saw the preview of your comment come up in my email, so I was going to paste the link to https://www.w3.org/TR/html52/infrastructure.html#space-characters and then I see you already found it. 😆

So 👍 !

**Comment by garretwilson** [comment]
> Okay, so being strict and accurate with the whitespace detection in HTML matters.

"… being strict and accurate … matters." Thought of the day. 😉

**Comment by garretwilson** [comment]
There is I suppose the question of whether you should wrap on characters that Unicode has marked as "whitespace" in the Unicode Character Database. For example the `MEDIUM MATHEMATICAL SPACE` character `U+205F` is marked as Unicode "whitespace". The problem with wrapping on Unicode whitespace characters is the same one as NBSP: when you wrap, I presume js-beautify would _replace_ the character with a newline (and perhaps tabs). The problem is that doing so would result in removal of this character with special semantics. The other option would be to keep it and still wrap, which would result in the _addition_ of ASCII whitespace that wasn't there before.

So after this short little conversation with myself 😆 I think my earlier conclusion (and that of @bitwiseman ) is the correct one: only wrap on the characters HTML5 considers whitespace, and we'll all be happy.

Thank you for bearing with this brief interlude. 😉

**Pull request merged**
