### PR TITLE
support for handlebars block comments {{!--...--}}

### PR DESCRIPTION
**Pull request by jaichandra**
fixes https://github.com/beautify-web/js-beautify/issues/930

### CODE REVIEW

**Comment by bitwiseman** [comment]
Hello, I'm sorry for the delay.  I've had no time to review changes or to fix the issue with the CI tools. Please be patient.

**Comment by bitwiseman** [comment]
@jaichandra - the CI tools are working.  If you fix your build break and add a few tests, I could merge your fix and you'd no longer have to maintain a fork.

**Comment by jaichandra** [comment]
@bitwiseman can't figure out why build is failing. My repo is in sync with the master. Need help.

**Comment by bitwiseman** [comment]
https://ci.appveyor.com/project/beautify-web/js-beautify/build/1.6+315 
run `./build` locally, commit any file changes made by that command, push those changes.

**Comment by jaichandra** [comment]
Thanks.. All checks passed now.

**Comment by bitwiseman** [comment]
Excellent! 

Now, please squash your commits into one commit, rebase on the current `master`, and add tests to https://github.com/beautify-web/js-beautify/blob/master/test/data/html/tests.js .  Run `./build jstest` as needed to generate and run tests.  

Once we have tests, we can merge.

**Comment by jaichandra** [comment]
Added tests.

**Comment by bitwiseman** [comment]
@jaichandra - Cool, that's a good start, but the bug refers to handlebars *inside* a handlebars  comment.  Please add tests for that scenario, and then we're good. 😄 

Thanks for persevering on this.

**Comment by bitwiseman** [comment]
@jaichandra - Your tests revealed a minor bug in the existing tests, which I fixed, then rebased your (squashed to one commit) changes on top of.  

This will go out in the next release. Thanks!

**Comment by jaichandra** [comment]
Thanks @bitwiseman

**Pull request closed without merging**
