### PR TITLE
feat(beautify-html): add 'skip_jinja' option

### PR DESCRIPTION
**Pull request by actionless**
That adds some basic supoprt for Jinja templating language.

### CODE REVIEW

**Comment by actionless** [comment]
btw, i am not sure what can be a better name for this option

**Comment by bitwiseman** [comment]
Great!  Please add some tests that show how this working.

**Comment by bitwiseman** [comment]
@actionless - This is a great start please squash your changes into one commit and add tests that verify the functionality.

**Comment by actionless** [comment]
i was trying to write few tests but realized what the current implementation (parsing any jinja tag as single tag) is working more or less only for templates of our application where we don't have too much jinja

i am not sure i'll be able to fix it properly any time soon so feel free to close it or leave it open in case if me or somebody else will pick it up later on

**Comment by bitwiseman** [comment]
@actionless - Any time to work on this?

**Comment by actionless** [comment]
nope, i am not working on that project where I was using Jinja anymore

feel free to close/adopt

**Pull request closed without merging**
