### PR TITLE
Remove moot `version` property from bower.json

### PR DESCRIPTION
**Pull request by kkirsche**
Per bower/bower.json-spec@a325da3

### CODE REVIEW

**Comment by bitwiseman** [comment]
It says "moot at the moment".  It costs almost nothing to keep this updated right now.  Is there a real win for removing it?

**Comment by kkirsche** [comment]
Also just an FYI there are discussions to move bower to NPM anyway so I wouldn't really plan to support it for ever: bower/bower#1520. I think it's a bad decision to encourage bower / keep unused properties

**Comment by kkirsche** [comment]
Also their maintainer says they probably won't ever use it: http://stackoverflow.com/questions/24844901/bowers-bower-json-file-version-property

**Comment by bitwiseman** [comment]
Thanks! One less thing I need to do for releases.

**Pull request merged**
