### PR TITLE
Fix erroneous newline added on @extend statements

### PR DESCRIPTION
**Pull request by TomAnthony**
# Description
- [x] Source branch in your fork has meaningful name (not `master`)

Fixes Issue: https://github.com/beautify-web/js-beautify/issues/1799

I'm unsure if this needs new tests?

# Before Merge Checklist 
These items can be completed after PR is created.

(Check any items that are not applicable (NA) for this PR)

- [x] JavaScript implementation
- [x] Python implementation (NA if HTML beautifier)
- [ ] Added Tests to data file(s)
- *NA* ~Added command-line option(s) (NA if~
- *NA* ~README.md documents new feature/option(s)~

### CODE REVIEW

**Comment by bitwiseman** [comment]
@TomAnthony 
Yes, this needs new tests. The old ones didn't catch this issue so we need tests to cover it.

**Comment by bitwiseman** [comment]
@TomAnthony  Do you plan to write tests for this?

**Comment by TomAnthony** [comment]
@bitwiseman - it is on my list to do, but I'm not familiar with the test setup so it would need a bit of time, which I'm short on at the moment.

If someone else wants to dive in to write some tests that would be great, otherwise I will try to get to it.

**Comment by TomAnthony** [comment]
@bitwiseman - I have added a test for this now. 

 I'm not v. familiar with the test setup, so please check, but I can confirm it fails on the current `main` branch, but passes on this branch.
 
 Thanks again for the plugin! :)

**Review by bitwiseman — APPROVED** [review]

**Pull request merged**
