### PR TITLE
Comment wrapping

### PR DESCRIPTION
**Pull request by bitwiseman**
# Description
- [x] Source branch in your fork has meaningful name (not `master`)

Fixes Issue: 
#1641

# Before Merge Checklist 
These items can be completed after PR is created.

(Check any items that are not applicable (NA) for this PR)

- [x] JavaScript implementation
- [x] Python implementation (NA if HTML beautifier)
- [x] Added Tests to data file(s)
- [x] Added command-line option(s) (NA if
- [x] README.md documents new feature/option(s)

### CODE REVIEW

**Comment by bitwiseman** [comment]
@HanabishiRecca 
If you have a minute to look this over, that'd be great.

**Comment by HanabishiRecca** [comment]
Comments formatting? I don't think this is a good idea because
1. Comments can be used for some decorative purposes. This means content must stay untouched.
Example:
```
<!--
                ._______________.
                |               |
                |   ATTENTION   |
                |_______________|

Please, keep the code clean, don't use things like this
<style>.a{}.b{}.c{}.d{}</style>

Use formatting!
<style>
    .a {}
    .b {}
    .c {}
    .d {}
</style>
-->
```
2. Using html comments inside the script and style blocks is a very bad practice.

So I think best way is completley ignore comments.

**Comment by bitwiseman** [comment]
@HanabishiRecca  
Ah, I should have provided context. 
Yes, putting html comments in style and script is not recommended,  but it is supported and people do it.  😭 

I see your point about not formatting what is inside comments.  
However, when they are used inside script and style tags, they have specific and well defined behavior and the stuff inside the comment needs to be treated as style or script of the appropriate type:

https://www.w3.org/TR/REC-html40/interact/scripts.html#h-18.3.2
https://www.w3.org/TR/CSS21/syndata.html#comments

This change doesn't perfectly model those two specification, but it is better and cleaner than what is there now, fixing #1641.  It also fixes the html tokenizer to correctly handle this input (which it would fail on before): 

```
<script>
    <!--
    var a = "</script>";
    // before this change the html beautifier would think that the script tag ended on the line above
    -->
</script>
```

**Comment by HanabishiRecca** [comment]
@bitwiseman, I just think this is not necessary. Because we can't recognize what exactly in the comment section. For people with a such bad style (why just not to move this code to the external js file?) I don't think they care about this.

So I suggest of course detect comments (to avoid `var a = "</script>";` situations) but really ignore insides.

**Comment by HanabishiRecca** [comment]
CDATA is another complicated case. For example I can do
```
alert(/*<![CDATA[*/'<!-- This will be the real js string, not a comment -->'/*]]>*/);
```
изображение


Any random insertions will be syntatically valid
```
var a = 
//<![CDATA[
'<!-- bla -->'
//]]>
;
alert(a);
```
изображение
etc.

So I don't think we want to mess with all this s**t :sweat_smile:

**Comment by bitwiseman** [comment]
This change only effects the one case where you have `<script>` or `<style>` followed immediately by a `<!--` or `<![CDATA[`.   All other cases, including your last examples, are unaffected. 

We already do support beautifying this: 

```
<script>
    <!--
    var a = "Hello, world.";
    -->
</script>
```

I understand that you believe that we should not support this, but that isn't an option.  This change makes the existing feature more robust and makes it work for style tags as well.  Do you have any comments/suggestions on the code?

**Comment by bitwiseman** [comment]
@HanabishiRecca 
On a related topic - Would you like to be involved in triaging features and fixes?  Mostly I've been making those choices and putting items that pass the bar or are higher priority into the current milestone.  If you'd like to be more involved, I'm happy to discuss that, but understand there's a lot of history to consider.

**Comment by HanabishiRecca** [comment]
> This change only effects the one case where you have `<script>` or `<style>` followed immediately by a `<!--` or `<![CDATA[`. All other cases, including your last examples, are unaffected.

Oh, ok then.

> Would you like to be involved in triaging features and fixes?

Unfortunately I don't have enough time to serious dive in development.

**Comment by bitwiseman** [comment]
@HanabishiRecca 
> Unfortunately I don't have enough time to serious dive in development.

Okay, cool.  I want to make sure that you know I am open to input and collaboration in general and that I value your feedback.

**Pull request merged**
