### PR TITLE
undindent-chained-methods option. Resolves #482

### LINKED ISSUE #482: daisy-chain indentation leads to over-indentation
Using this via https://github.com/enginespot/js-beautify-sublime

Expected:

```
object
.foo()
.bar();
```

Actual:

```
object
  .foo()
  .bar();
```

To illustrate the problem: the current indenting can lead to EOFs like this:

```
      });
    });
})();
```

That looks like an error to me, and will prompt me to look for the cause &ndash; or worse, make me blind to the real ones =(

### PR DESCRIPTION
**Pull request by aecepoglu**

### CODE REVIEW

**Comment by aecepoglu** [comment]
I didn't test the `unindent-chained-methods` option in combinations with other options. Also I didn't test the python side manually.

Let me know if there is anything missing

**Comment by brandondrew** [comment]
👍 Hallelujah!

**Comment by aecepoglu** [comment]
I was going to squash the commits together. I wasn't sure whether github did that automatically or not.

**Comment by pietrovismara** [comment]
@aecepoglu Thank you so much man, now it's my turn to go to atom-beautify repo and press them to update js-beautify.

**Comment by bitwiseman** [comment]
@aecepoglu - I could do the squash as part of merging the PR, but I just didn't. 😄  No big deal.

**Comment by bitwiseman** [comment]
@aecepoglu - also, I need to release the new version before you can do that.

**Pull request merged**
