### PR TITLE
[Issue #1988] Added support to recognize Handlebars block with whitespace control

### LINKED ISSUE #1988: Fails to recognize Handlebars block with whitespace control, e.g. {{~#if true ~}}
# Description

Handlebars supports [whitespace control](https://handlebarsjs.com/guide/expressions.html#whitespace-control) by putting `~` on one or both sides of any double-brace-enclosed statement. But js-beautify fails to recognize a statement with whitespace control, resulting in incorrect indentation.

# Input
The code looked like this before beautification:
```handlebars
{{#if true}}<div><div>
{{~#if true ~}}<p>true</p>{{/if}}
</div></div>{{/if}}
```

# Expected Output
The code should have looked like this after beautification:
```handlebars
{{#if true}}
    <div>
        <div>
            {{~#if true ~}}
                <p>true</p>
            {{/if}}
        </div>
    </div>
{{/if}}
```

# Actual Output
The  code actually looked like this after beautification:
```handlebars
{{#if true}}
    <div>
        <div>
            {{~#if true ~}}
            <p>true</p>
{{/if}}
</div>
</div>{{/if}}
```

# Steps to Reproduce
`html-beautify -H test.hbs`

## Environment
OS: Linux

## Settings
None

### PR DESCRIPTION
**Pull request by zalsaedy**
# Description
- [x] Source branch in your fork has meaningful name (not `main`)

Fixes Issue: 
#1988 "Fails to recognize Handlebars block with whitespace control, e.g. {{~#if true ~}}"

Added the whitespace control character inside the `tag_check_match` for the html beautifier. The control character also affected the token for partial handlebars `{{#>` to `{{~#>` which I also added a check for. Additionally, if the character is included at the start of handlebars, the test for non single handlebars tags will start at character 3 instead of character 2.

I added unit tests checking that issue 1988 was fixed, and that previous handlebar formatting fixes would not break with the inclusion of "~" at the start.

# Before Merge Checklist 
These items can be completed after PR is created.

(Check any items that are not applicable (NA) for this PR)

- [x] JavaScript implementation
- [NA] Python implementation (NA if HTML beautifier)
- [x] Added Tests to data file(s)
- [NA] Added command-line option(s) (NA if
- [NA] README.md documents new feature/option(s)

### CODE REVIEW

**Review by bitwiseman — APPROVED** [review]

**Comment by bitwiseman** [comment]
@zalsaedy 
I can't see the diff for your last commit (on my phone GitHub app) but the number of changes indicates to me something amiss. I see that the checks pass but... Could you sanity check that last commit?

**Comment by zalsaedy** [comment]
Hi @bitwiseman, just went through the last diff. In the old version, I closed the list of tests of tests as "}]" (on the same line), while in the new version the "]" was separated onto a new line. For some reason, this causes the diff to believe that most of the file altered was deleted and added with new text, even though the new text matches the old one.

I just went through manually and confirmed that there were no changes except the last 2 lines due to the separation of "}]", which was intentional.

**Comment by bitwiseman** [comment]
@zalsaedy 

Ah, I see. Would you mind changing that back? Put them on the same line?

**Comment by zalsaedy** [comment]
Heads up: last commit does list a lot of changes, but it's due to whitespace indent issues. My text editor over-indented, but running "make ci" fixed it. I did not catch this earlier, but this was the same reason with the previous commit with the large number of changes.

**Comment by bitwiseman** [comment]
The total resulting changes for the PR look good again. Thanks for taking the time to clean it up.

**Review by bitwiseman — APPROVED** [review]

**Pull request merged**
