### PR TITLE
Add support for new record types (cont.)

### LINKED ISSUE #2062: Erroneous output with upcoming Records syntax
# Description

Records are a new primitives in Javascript, and they are currently being implemented in Firefox (See https://bugzilla.mozilla.org/show_bug.cgi?id=1658309, https://bugzilla.mozilla.org/show_bug.cgi?id=1774360 and https://github.com/tc39/proposal-record-tuple)

Records are instantiated like objects, but with a hash before the curly bracket, e.g. `#{ hello: "world" }`

# Input
The code looked like this before beautification:
```js
#{ hello: "world" }
```

# Expected Output
The code should have looked like this after beautification:
```js
#{ 
  hello: "world"
}
```

# Actual Output
The  code actually looked like this after beautification:
```js
# { 
  hello: "world"
}
```

Notice the space between `#` and `{`.
If the output would be evaluated, it would result in a `SyntaxError`

# Steps to Reproduce

## Environment
OS: OSX

## Settings

Default settings, I ran `echo "#{hello: 'world'}" | npx js-beautify`

---

Let me know if I can be of any help

### PR DESCRIPTION
**Pull request by antoniusanggito**
# Description
- [X] Source branch in your fork has meaningful name (not `main`)

Fixes #2062 
Continuing from pull request #2099 

# Before Merge Checklist 
These items can be completed after PR is created.

(Check any items that are not applicable (NA) for this PR)

- [X] JavaScript implementation
- [X] Python implementation (NA if HTML beautifier)
- [x] Added Tests to data file(s)
- [NA] Added command-line option(s) (NA if
- [NA] README.md documents new feature/option(s)

### CODE REVIEW

**Comment by bitwiseman** [comment]
You might do better If you changed the tokenizer to recognize `#{` as a `START_BLOCK` token the same as `{`. I don't know of any case where we would want to separate `#{` wheb the user enters them together.  

If `#{` occurs at a point where the record syntax would not be valid, I think we still want to treat it as though it were valid to avoid bad behavior.

**Comment by antoniusanggito** [comment]
The checklists are done now. Let me know for any updates from your review.

Sorry for a bit messy history while I was trying to rename the commit message.

**Comment by antoniusanggito** [comment]
The make commands are passed on my end now

**Comment by bitwiseman** [comment]
Delete the `.DS_store` file, please.

**Comment by antoniusanggito** [comment]
Done, brought it back.. it was deleted accidentally

**Comment by bitwiseman** [comment]
Well done! Thanks!

**Pull request merged**
