### PR TITLE
New option: indent_empty_lines

### PR DESCRIPTION
**Pull request by HanabishiRecca**
This option allows to keep indentation on empty lines.

### CODE REVIEW

**Comment by HanabishiRecca** [comment]
@bitwiseman, check the current state.

**Comment by bitwiseman** [comment]
@HanabishiRecca
Looking good.  Seriously, great work, thank you. 
I was wrong about this being complete - need to add the setting to the commandline processors and the README.md .

**Comment by HanabishiRecca** [comment]
I think done

**Comment by bitwiseman** [comment]
@HanabishiRecca 
I want more contributors like you.

**Pull request merged**
