### PR TITLE
Fixes issue #587 for javascript implementation

### PR DESCRIPTION
**Pull request by rlindner81**
Simple fix to interpret ident-with-tabs option in javascript implementation

### CODE REVIEW

**Comment by bitwiseman** [comment]
@rlindner81 - execellent!  Please add the python implementation for the css (it is easy, trust me) and add some tests to https://github.com/beautify-web/js-beautify/tree/master/test/data.  (The change to the data files will result in change to generated test files.  Check those in as well.)

**Comment by rlindner81** [comment]
I added the python implementation for CSS (it was easy). I did not see any tests for the indent_with_tabs option (even for js). Can you point them out?

**Comment by bitwiseman** [comment]
Looks like your python needs a tweak.   Before you push, run `make` from root if you want to test your changes. (This will report failure if you have files checked out.) 
There might now be any tests for this option.  Look at 
https://github.com/beautify-web/js-beautify/blob/master/test/data/javascript.js#L48 for an example of what a test section might look like.  But yours can be much shorter and simpler. :smile: 

Here is an example of a simple change: 
https://github.com/beautify-web/js-beautify/commit/46cf32151a6378814a13d3d8c925e1c649ba41ac

https://github.com/beautify-web/js-beautify/commit/46cf32151a6378814a13d3d8c925e1c649ba41ac

to see what a basic option test looks like.

**Comment by rlindner81** [comment]
Well that was fun.

**Comment by rlindner81** [comment]
@bitwiseman Still unhappy?

**Comment by kudou** [comment]
@bitwiseman STILL NOT WORK

**Comment by rlindner81** [comment]
@kudou Please avoid all caps. And be explicit with what you mean. What isn't working?

**Pull request merged**
