### PR TITLE
Adds #916

### PR DESCRIPTION
**Pull request by cfischer**
wrap_attributes: 'force',
wrap_attributes_indent_size: 'align',
reformat_unformatted_tags: true

### CODE REVIEW

**Comment by cfischer** [comment]
Closes #916

**Comment by bitwiseman** [comment]
Hello, I'm sorry for the delay.  I've had no time to review changes or to fix the issue with the CI tools. Please be patient.

**Comment by bitwiseman** [comment]
It looks like we still have failures.  Please take a look when you get a chance.

**Comment by bitwiseman** [comment]
@cfischer - please take a look and add tests.  You can run `./build` to verify your feature is working at expected.

**Comment by Lukinos** [comment]
@bitwiseman - I did not see this pull request, and hence I also coded this feature (https://github.com/Lukinos/js-beautify/commit/341052954730390714e32846419097889f807d58). But what I wanted to know is how it should be tested. Because, the test ecosystem seems to be too rigid.

Concretely, I wanted to add my tests to the 'wrap_attributes' tests (name: AttributeWrap), however the 'indent'_attr' value is fixed through all tests (for one entry matrix) and as we want to test something where the 'indent_attr' is dynamic for each test, the tests break.

What would be the right way to do ? Creating several specific groups just for this new attribute ? Something else ?

**Comment by bitwiseman** [comment]
@Lukinos - Please create a new pull request and try adding one test where you think it should go (even if it fails). Then I'll be able to give you concrete feedback.

**Pull request closed without merging**
