### PR TITLE
Branding

### PR DESCRIPTION
**Pull request by SNDST00M**
## Description
- [x] Source branch in your fork has meaningful name (not `main`)

This pull adds branding assets for the js-beautifier repository.

Fixes Issue: #1936

## Images
<del>Old</del>

<ins>New</ins>

website screenshot

light banner dark banner

light wordmark dark wordmark

# Before Merge Checklist 
These items can be completed after PR is created.

(Check any items that are not applicable (N/A) for this PR)

- [x] JavaScript implementation
- [x] Python implementation (N/A if HTML beautifier)
- [x] Added Tests to data file(s)
- [x] Added command-line option(s) (N/A if
- [x] README.md documents new feature/option(s)

### CODE REVIEW

**Comment by bitwiseman** [comment]
@4086606 
Thanks for doing this.  It looks really good. 
I have a mild concern, which is that the beautifier is actually not just JS.  The website is https://beautifier.io/ and it currently also works on CSS and HTML.  So, the JS is a bit misleading.  

On the other hand, "js-beautify" is the name of the project - the repo, the npm package. 

Would you be willing to do something in this style, yellow and grey lines of a flower, like the tulip icon: 🌷 
If not, that's fine, it is better to has some logo rather than none and change it later if needed.

Thanks again.

**Comment by 4086606** [comment]
Would love to go in a different direction than the current one.
A flower drawn in lines is a great and unique idea, I'll look into it tomorrow 😪

**Comment by 4086606** [comment]
@bitwiseman how does https://github.com/beautify-web/js-beautify/pull/1951#issue-682785310 look now?

**Comment by bitwiseman** [comment]
I like it!

**Review by bitwiseman — APPROVED** [review]

**Comment by bitwiseman** [comment]
@4086606  This is looks great but I need to fix the CI build to merge it.  Thanks for your patience.

**Comment by kayal28** [comment]
> ## Description
> * [x]  Source branch in your fork has meaningful name (not `main`)
> 
> This pull adds branding assets for the js-beautifier repository.
> 
> Fixes Issue: #1936
> 
> ## Images
> icon icon
> 
> website screenshot
> 
> light banner dark banner
> 
> light wordmark dark wordmark
> 
> # Before Merge Checklist
> These items can be completed after PR is created.
> 
> (Check any items that are not applicable (N/A) for this PR)
> 
> * [x]  JavaScript implementation
> * [x]  Python implementation (N/A if HTML beautifier)
> * [x]  Added Tests to data file(s)
> * [x]  Added command-line option(s) (N/A if
> * [x]  README.md documents new feature/option(s)

**Comment by SNDST00M** [comment]
Nice!

**Pull request merged**
