### PR TITLE
Remove Python interdependency (Fixes #1808)

### LINKED ISSUE #1808: pip install cssbeautifier fails
Pip installing cssbeautifier fails with the following message:
```
$ python3 -m pip install cssbeautifier --user
Collecting cssbeautifier
  Downloading cssbeautifier-1.11.0.tar.gz (22 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-9m8ry79r/cssbeautifier/setup.py'"'"'; __file__='"'"'/tmp/pip-install-9m8ry79r/cssbeautifier/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ud0acpi6
         cwd: /tmp/pip-install-9m8ry79r/cssbeautifier/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-9m8ry79r/cssbeautifier/setup.py", line 7, in <module>
        from jsbeautifier.__version__ import __version__
    ModuleNotFoundError: No module named 'jsbeautifier'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

It does not seem to matter if jsbeautifier is installed or not. I believe this is a packaging issue because if I git clone the repo and run `python3 -m pip install -e python/` both cssbeautifier and jsbeautifier are installed successfully (and work great!).

Side note: That led me to wonder if I could install both cssbeautifier and jsbeautifier by running `python3 -m pip install jsbeautifier`. So I tried and only jsbeautifier is installed (as expected).

### PR DESCRIPTION
**Pull request by thp**
# Description

- [x] Source branch in your fork has meaningful name: `python-interdependency`

Installing jsbeautifier and cssbeautifier at the same time fails, because the cssbeautifier `setup.py` tries to
import `jsbeautifier.__version__` (which is not installed at that time).

As long as both are separate packages, it makes sense for them to have their own version information (even if they are kept in sync).

This way, the packages can be installed separately and in any order without problems.

Fixes Issue: #1808, https://github.com/thp/urlwatch/issues/526

# Before Merge Checklist 
These items can be completed after PR is created.

(Check any items that are not applicable (NA) for this PR)

- NA JavaScript implementation
- [ ] Python implementation (NA if HTML beautifier)
- NA Added Tests to data file(s)
- NA Added command-line option(s) (NA if
- [ ] README.md documents new feature/option(s)

### CODE REVIEW

**Comment by thp** [comment]
..and apart from the interdependency fix, this is more "correct" (because the installed `jsbeautifier` version could be a different version than the installed `cssbeautifier` version, right now it will always show the `jsbeautifier` version for `cssbeautifier` too, even if `cssbeautifier` is in fact newer or older).

**Comment by captbrando** [comment]
Gotcha. I'll give that a shot as the manual version still gave me trouble. Definitely something upstream.

```
$ python3 -m pip install jsbeautifier
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting jsbeautifier
  Using cached https://www.piwheels.org/simple/jsbeautifier/jsbeautifier-1.11.0-py3-none-any.whl
Collecting six>=1.13.0 (from jsbeautifier)
  Downloading https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
Collecting editorconfig>=0.12.2 (from jsbeautifier)
  Downloading https://www.piwheels.org/simple/editorconfig/EditorConfig-0.12.2-py3-none-any.whl
Installing collected packages: six, editorconfig, jsbeautifier
  Found existing installation: six 1.12.0
    Not uninstalling six at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'six'. No files were found to uninstall.
Successfully installed editorconfig-0.12.2 jsbeautifier-1.11.0 six-1.15.0

$ python3 -m pip install cssbeautifier
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting cssbeautifier
  Using cached https://files.pythonhosted.org/packages/0f/64/f3cdac9461be42f6c359810ba4cbe23363d1edfafad7a3d49b5fe8a58d2a/cssbeautifier-1.11.0.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/jsbeautifier.egg-info
    writing pip-egg-info/jsbeautifier.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/jsbeautifier.egg-info/dependency_links.txt
    writing entry points to pip-egg-info/jsbeautifier.egg-info/entry_points.txt
    writing requirements to pip-egg-info/jsbeautifier.egg-info/requires.txt
    writing top-level names to pip-egg-info/jsbeautifier.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/jsbeautifier.egg-info/SOURCES.txt'
    error: package directory 'jsbeautifier' does not exist

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-35u12eo0/cssbeautifier/
```

**Comment by bitwiseman** [comment]
@thp 
Made one additional change related to the release script, but otherwise this looks good to me.

**Comment by tysmith** [comment]
Thank you for the fix :)

**Pull request merged**
