### PR TITLE
base52 unpacker support

### PR DESCRIPTION
**Pull request by doomedraven**
this will correctly unpack base52 packed js and will replace the rest needed stuff, it must be replaced before unpack

### CODE REVIEW

**Comment by bitwiseman** [comment]
I'm really hesitant to add more packer support.  Could you give a bit more context for this?

**Comment by doomedraven** [comment]
hello, ok let's see, i just download the code of python from this repo, replaced unpack.py with my code update:

```
packed_js = """eval(function(p,a,c,k,e,d){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--){d[e(c)]=k[c]||e(c)}k=[function(e){return d[e]}];e=function(){return'\\w+'};c=1};while(c--){if(k[c]){p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c])}}return p}('r w(t,c){5 9="s q.x.v.u:o;";5 7=n f(\'*.h.e.1\',\'*.d.1\',\'*.g.2.1\',\'*.j.2.1\',\'*.m.l.k.1\',\'*.p.2.1\',\'*.G.2.1\',\'*.K.2.1\',\'*.J.2.1\',\'*.1-3.I.1\',\'*.M.2.1\',\'*.P-3.2.1\',\'*.y.2.1\',\'*.N.2.1\',\'*.L.2.1\',\'*.H.2.1\',\'B.a.2.1\',\'A.8.2.1\',\'4-3.2.1\',\'6.4-3.2.1\',\'z.4-3.2.1\',\'6.a.2.1\',\'6.8.2.1\');C(5 i=0;i<7.D;i++){F(E(c,7[i])){b 9}}b"O"}',52,52,'|jp|co|bank|rakuten|var|www|hosts|japannetbank|proxy|smbc|return|host|tracer|mufg|Array|mizuhobank|bk||boy|ne|anser|parasol|new|80|chibabank|185|function|SOCKS|url|109|216|FindProxyForURL|82|hokkokubank|fes|login|direct|for|length|shExpMatch|if|juroku|miyagin|japanpost|chugin|82bank|yamagatabank|awabank|musashinobank|DIRECT|daishi'.split('|'),0,{}))"""

from jsbeautifier.unpackers import packer
print packer.unpack(packed_js)
function FindProxyForURL(url,host){var proxy="SOCKS 185.82.216.109:80;";var hosts=new Array('*.bk.mufg.jp','*.tracer.jp','*.mizuhobank.co.jp','*.boy.co.jp','*.parasol.anser.ne.jp','*.chibabank.co.jp','*.juroku.co.jp','*.82bank.co.jp','*.chugin.co.jp','*.jp-bank.japanpost.jp','*.awabank.co.jp','*.daishi-bank.co.jp','*.hokkokubank.co.jp','*.musashinobank.co.jp','*.yamagatabank.co.jp','*.miyagin.co.jp','direct.smbc.co.jp','login.japannetbank.co.jp','rakuten-bank.co.jp','www.rakuten-bank.co.jp','fes.rakuten-bank.co.jp','www.smbc.co.jp','www.japannetbank.co.jp');for(var i=0;i<hosts.length;i++){if(shExpMatch(host,hosts[i])){return proxy}}return"DIRECT"}
```

Today i [found](http://forum.opencart.com/viewtopic.php?t=15387) __base45__ packed js, if everything is fine with this, i will add other one a bit later when will have time, as it not supported at the moment:

```
eval(function(p,a,c,k,e,d){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--){d[e(c)]=k[c]||e(c)}k=[function(e){return d[e]}];e=function(){return'\\w+'};c=1};while(c--){if(k[c]){p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c])}}return p}('$(a).x(p(){5(!a.n(l)){b s}4 k=z A(a.D);4 7,d,6;5(k.q(\'?\')==-1){b s}7=k.c(\'?\');7=7[1].c(\'&\');o(4 i B 7){d=7[i].c(\'=\');5(d[0]==\'y\'){6=C(d[1]);6=6.c(\' \');o(4 j=0;j<6.8;j++){5(6[j].8>=3){r(6[j])}}b h}}b h});p r(e){4 2=a.n(l).v;4 g=\'\';4 i=-1;4 w=e.m();4 9=2.m();H(2.8>0){i=9.q(w,i+1);5(i<0){g+=2;2=\'\'}E{5(2.f(\'>\',i)>=2.f(\'<\',i)){5(9.f(\'/u>\',i)>=9.f(\'<u\',i)){g+=2.G(0,i)+F+2.t(i,e.8)+I;2=2.t(i+e.8);9=2.m();i=-1}}}}a.n(l).v=g;b h}',45,45,'||bodyText||var|if|keywords|parts|length|lcBodyText|document|return|split|keyValue|searchTerm|lastIndexOf|newText|true|||href|CONTAINER_ID|toLowerCase|getElementById|for|function|indexOf|doHighlight|false|substr|script|innerHTML|lcSearchTerm|ready|keyword|new|String|in|decodeURI|location|else|HIGHLIGHT_START|substring|while|HIGHLIGHT_END'.split('|'),0,{}));


In [9]: print packer.unpack(packed_js)
---------------------------------------------------------------------------
UnpackingError                            Traceback (most recent call last)
<ipython-input-9-86fac54e215e> in <module>()
----> 1 print packer.unpack(packed_js)

PATH/jsbeautifier/unpackers/packer.py in unpack(source)
     38         unbase = Unbaser(radix)
     39     except TypeError:
---> 40         raise UnpackingError('Unknown p.a.c.k.e.r. encoding.')
     41
     42     def lookup(match):

UnpackingError: Unknown p.a.c.k.e.r. encoding.
```

* Other thing what i personally prefer, as you and me and few more person know is what this kind of packed stuff based on bases, to show 
something like 
`        raise UnpackingError('Unknown p.a.c.k.e.r. encoding., Base: {0}'.format(radix))`
istead of just unknown, as you have idx
`UnpackingError: Unknown p.a.c.k.e.r. encoding., Base: 45`

**Comment by doomedraven** [comment]
lol, to unpack 45, just add this is enough, i think that packers start put fake base number, this is just a copy of 62 from your script
45 : '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ',

and works awesome, tested with eval unpacked version, and this 45, result is the same

**Comment by bitwiseman** [comment]
Related to #782

**Comment by bitwiseman** [comment]
I'm going move this out to 2.0.  The test infrastructure for this area is completely insufficient to confidently take updates.

**Comment by esseks** [comment]
There are a few unclear points in your PR:

1. It looks like there is a lot of base52-specific behaviour introduced, if compared to how base62 and base95 are handled. The original implementation was written so that adding a new encoding was just a matter of registering a new alphabet, so I am genuinely curious about what warrants this exception.

2. I am not certain why you would add base36 alphabet in this commit ([line 86](https://github.com/beautify-web/js-beautify/commit/6c958a6622fd6b5cccad4187ea5cffcbad3e0966#diff-0d1071e84973fbdb009844118ee09788R86)). Also notice that base36 is handled by Python built-in `int` and that this fact is already taken in consideration ([line 103](https://github.com/beautify-web/js-beautify/blob/6c958a6622fd6b5cccad4187ea5cffcbad3e0966/python/jsbeautifier/unpackers/packer.py#L103)). 

3. Why did you [add base alphabets in the documentation of the ctor?](https://github.com/beautify-web/js-beautify/commit/6c958a6622fd6b5cccad4187ea5cffcbad3e0966#diff-0d1071e84973fbdb009844118ee09788R93). Alphabets are internal to the implementation, the user only needs to know that `Unbaser` can handle e.g. base52 or base62.

**Comment by bitwiseman** [comment]
Closing due to lack of response.

**Comment by doomedraven** [comment]
@esseks about 36 base agree, useless, but check how the base52 works, and you can see what is a bit different from another, at least on all packet js which i saw was impossible to get that works without that small fix

**Pull request closed without merging**
