### PR TITLE
Fix Issue #844

### PR DESCRIPTION
**Pull request by orottier**
Less beautifier: 

> Properties can be interpolated, e.g. @{prefix}-property: value

### CODE REVIEW

**Comment by orottier** [comment]
Iterative development, we're getting there

**Comment by bitwiseman** [comment]
Okay. :+1:

**Comment by orottier** [comment]
Probably related: #628

**Comment by bitwiseman** [comment]
@orottier - Fantastic start!

It looks like you have a solution that stops the breaking result.  But it doesn't look like this beautify unformatted input.  For example, what happens when your input is `tag {@{prop}: none;}`?  
Could you add some additional tests for a wider set of inputs?

**Comment by bitwiseman** [comment]
Great, thanks!

**Pull request merged**
