### PR TITLE
Add unit tests for input scanner

### PR DESCRIPTION
**Pull request by ganes1410**
Added unittest for inputscanner file referring #1446.
Check whether it is ok @bitwiseman

### CODE REVIEW

**Comment by bitwiseman** [comment]
@ganes1410 Failing due to jshint failures.  Run`make js`, fix errors, and resubmit.

**Comment by bitwiseman** [comment]
Is your local branch up-to-date? Are you running from the project root?   What happens when you run `make` without any parameters?

**Comment by bitwiseman** [comment]
@ganes1410  
Did you give up?  Is there any way we can help?

**Comment by ganes1410** [comment]
@bitwiseman  No man.I have not been home for some days.Thats why i could not work on it.
When i try to run `make` without any parameters , it shows `make: *** No targets specified and no makefile found.  Stop.
`

**Comment by MacKLess** [comment]
Travis CI blew up on build 1976.4 but it does not appear to be caused by my code. Looks like the issue lies with Travis CI itself.

**Pull request merged**
