### PR TITLE
Update packer.py

### PR DESCRIPTION
**Pull request by swan46**
fixed elements 37...61 usage

### CODE REVIEW

**Comment by neskk** [comment]
Tested this and worked without problems where the previous version would fail.

**Comment by bitwiseman** [comment]
@neskk  What inputs did you use for testing?   If you have some minimal input/output examples, especially ones that failed before this change, that would be be great.

**Comment by neskk** [comment]
Here is a small script that contains two tests. `JS1` is ok but `JS2` fails to be unpacked.
[test.txt](https://github.com/beautify-web/js-beautify/files/1900871/test.txt)

**Comment by swan46** [comment]
I tested both with the newest packer.py, both pass the test:
$ python tmpjs2.py p6060.js
$(document).ready(function() {
$(\'.rdbbf\').html(8080);$(\'.r4af4\').html(80);$(\'.rad9e\').html(8000);$(\'.rfc13\').html(3128);$(\'.r2907\').html(53281);$(\'.r1315\').html(81);$(\'.rfbb3\').html(544);$(\'.r6277\').html(65205);$(\'.ra79b\').html(20183);$(\'.rfac9\').html(15600);$(\'.rcb41\').html(8088);$(\'.r64bb\').html(9000);$(\'.rf196\').html(9999);$(\'.r32d4\').html(62225);$(\'.r5973\').html(8888);$(\'.rcdcd\').html(65103);$(\'.r2342\').html(6660);$(\'.re3b6\').html(45618);$(\'.rfc3a\').html(65301);$(\'.r38f1\').html(8082);$(\'.r7712\').html(55555);$(\'.rcc99\').html(53282);$(\'.r3239\').html(52136);$(\'.r3ebb\').html(3129);$(\'.r4178\').html(8090);$(\'.rf9ec\').html(54214);$(\'.rd77c\').html(41525);$(\'.r5654\').html(10000)});
$ python tmpjs2.py p6282.js
$(document).ready(function() {
$(\'.r6f9e\').html(80);$(\'.ra7c2\').html(8080);$(\'.r7f55\').html(8000);$(\'.r257a\').html(8888);$(\'.r33d8\').html(53281);$(\'.r1973\').html(3128);$(\'.reaa3\').html(41239);$(\'.r7549\').html(544);$(\'.r6032\').html(65205);$(\'.r4620\').html(20183);$(\'.r7641\').html(8081);$(\'.r776a\').html(8118);$(\'.r0515\').html(3129);$(\'.r5a69\').html(90);$(\'.rd0d1\').html(9000);$(\'.r9c14\').html(8060);$(\'.reba4\').html(61234);$(\'.rddb3\').html(9999);$(\'.rdda0\').html(53005);$(\'.r8d1f\').html(63909);$(\'.r3a9b\').html(65103);$(\'.r2e35\').html(45618);$(\'.r40f7\').html(62225);$(\'.r1ed6\').html(65309);$(\'.rc7de\').html(3355);$(\'.r4129\').html(41525);$(\'.rffd8\').html(53282);$(\'.r0a1b\').html(8123);$(\'.r6912\').html(1080);$(\'.r4398\').html(55555);$(\'.r169c\').html(54214);$(\'.r2951\').html(6666);$(\'.rd969\').html(45619);$(\'.rc4ca\').html(8088);$(\'.r1af5\').html(9090);$(\'.rdad6\').html(8980);$(\'.re1ee\').html(443);$(\'.r7c10\').html(87);$(\'.rdf97\').html(6868)});


2018-04-12 02:08 keltezéssel, neskk írta:

**Comment by neskk** [comment]
I have a new test subject that seems to fail both versions but works in the online version - http://jsbeautifier.org/
[packed.txt](https://github.com/beautify-web/js-beautify/files/1905659/packed.txt)

```javascript
eval(function(p,a,c,k,e,r){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--){r[e(c)]=k[c]||e(c)}k=[function(e){return r[e]}];e=function(){return'\\w+'};c=1};while(c--){if(k[c]){p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c])}}return p}('m=D^C;n=8;k=2;o=B^E;b=3;l=5;d=4;e=F^A;s=6;c=G^I;f=0;i=y^u;g=w^z;a=x^v;h=1;r=7;j=H^M;t=T^U;p=9;q=V^X;J=f^j;W=h^i;R=k^g;S=b^a;L=d^e;K=l^m;N=s^t;O=r^q;Q=n^o;P=p^c;',60,60,'^^^^^^^^^^Two3Two^Zero^Eight6Six^Six^Seven0Seven^Eight^SevenNineEight^Four^Seven9Five^Four5Nine^Two^Five^EightEightOne^One^One6Three^Nine^TwoFourFour^Three^Seven^Eight8Zero^1080^9090^10249^5003^3351^6588^8088^8836^8080^7670^8118^6359^4639^4095^81^TwoSevenFourOne^Zero2SixThree^OneTwoNineEight^3127^FourSevenThreeSix^OneThreeEightFive^EightOneTwoSeven^Nine5ZeroTwo^Eight4FiveNine^One7OneZero^6208^8909^4583^Four2SevenFour^8090'.split('\u005e'),0,{}))
```

**Comment by swan46** [comment]
That packed file takes caret (^), utf code: \u005e,  as separation 
character.
Python code in _filterargs, however, assumes | as separation character.
Therefore this kind of packing never-ever worked in python.

How did you create this test file?
I use http://joliclic.free.fr/php/javascript-packer/en/index.php
This packer always uses | as separation character.
This one:http://dean.edwards.name/packer/ also always uses | as separator.

This version:

eval(function(p,a,c,k,e,r){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--)r[e(c)]=k[c]||e(c);k=[function(e){return 
r[e]}];e=function(){return'\\w+'};c=1};while(c--)if(k[c])p=p.replace(new 
RegExp('\\b'+e(c)+'\\b','g'),k[c]);return 
p}('a=u^v;b=8;c=2;d=w^x;e=3;f=5;g=4;h=y^z;i=6;j=A^B;k=0;l=C^D;m=E^F;n=G^H;o=1;p=7;q=I^J;r=K^L;s=9;t=M^N;O=k^q;P=o^l;Q=c^m;R=e^n;S=g^h;T=f^a;U=i^r;V=p^t;W=b^d;X=s^j;',60,60,'||||||||||EightEightOne|One|Two|One6Three|Zero|Five|Six|Seven0Seven|Seven|Eight6Six|Eight|Seven9Five|SevenNineEight|Two3Two|Four|Three|Four5Nine|Eight8Zero|Nine|TwoFourFour|7670|8080|8836|8118|6359|8088|4639|81|3351|1080|10249|6588|5003|9090|4095|3127|6208|8909|4583|8090|TwoSevenFourOne|Four2SevenFour|Eight4FiveNine|One7OneZero|OneTwoNineEight|Zero2SixThree|FourSevenThreeSix|OneThreeEightFive|Nine5ZeroTwo|EightOneTwoSeven'.split('|'),0,{}))

that uses | as separator, will be perfectly decoded by packer.py.

Also this one:

eval(function(p,a,c,k,e,d){while(c--){if(k[c]){p=p.replace(new 
RegExp('\\b'+c+'\\b','g'),k[c])}}return 
p}('22=39^38;23=8;20=2;24=37^40;11=3;21=5;13=4;14=41^36;28=6;12=42^44;15=0;18=34^30;16=32^35;10=33^31;17=1;27=7;19=43^48;29=55^56;25=9;26=57^59;45=15^19;58=17^18;53=20^16;54=11^10;47=13^14;46=21^22;49=28^29;50=27^26;52=23^24;51=25^12;',10,60,'||||||||||Two3Two|Zero|Eight6Six|Six|Seven0Seven|Eight|SevenNineEight|Four|Seven9Five|Four5Nine|Two|Five|EightEightOne|One|One6Three|Nine|TwoFourFour|Three|Seven|Eight8Zero|1080|9090|10249|5003|3351|6588|8088|8836|8080|7670|8118|6359|4639|4095|81|TwoSevenFourOne|Zero2SixThree|OneTwoNineEight|3127|FourSevenThreeSix|OneThreeEightFive|EightOneTwoSeven|Nine5ZeroTwo|Eight4FiveNine|One7OneZero|6208|8909|4583|Four2SevenFour|8090'.split('|')))

works perfectly with packer.py.

2018-04-13 04:51 keltezéssel, neskk írta:
> eval(function(p,a,c,k,e,r){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--){r[e(c)]=k[c]||e(c)}k=[function(e){return  r[e]}];e=function(){return'\\w+'};c=1};while(c--){if(k[c]){p=p.replace(new  RegExp('\\b'+e(c)+'\\b','g'),k[c])}}return  p}('m=D^C;n=8;k=2;o=B^E;b=3;l=5;d=4;e=F^A;s=6;c=G^I;f=0;i=y^u;g=w^z;a=x^v;h=1;r=7;j=H^M;t=T^U;p=9;q=V^X;J=f^j;W=h^i;R=k^g;S=b^a;L=d^e;K=l^m;N=s^t;O=r^q;Q=n^o;P=p^c;',60,60,'^^^^^^^^^^Two3Two^Zero^Eight6Six^Six^Seven0Seven^Eight^SevenNineEight^Four^Seven9Five^Four5Nine^Two^Five^EightEightOne^One^One6Three^Nine^TwoFourFour^Three^Seven^Eight8Zero^1080^9090^10249^5003^3351^6588^8088^8836^8080^7670^8118^6359^4639^4095^81^TwoSevenFourOne^Zero2SixThree^OneTwoNineEight^3127^FourSevenThreeSix^OneThreeEightFive^EightOneTwoSeven^Nine5ZeroTwo^Eight4FiveNine^One7OneZero^6208^8909^4583^Four2SevenFour^8090'.split('\u005e'),0,{}))

**Comment by bitwiseman** [comment]
@swan46 replied via email.  I'm reposting with markdown. 

That packed file takes caret (^), utf code: \u005e,  as separation 
character.
Python code in _filterargs, however, assumes | as separation character.
Therefore this kind of packing never-ever worked in python.

How did you create this test file?
I use http://joliclic.free.fr/php/javascript-packer/en/index.php
This packer always uses | as separation character.
This one:http://dean.edwards.name/packer/ also always uses | as separator.

This version:

```
eval(function(p,a,c,k,e,r){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--)r[e(c)]=k[c]||e(c);k=[function(e){return 
r[e]}];e=function(){return'\\w+'};c=1};while(c--)if(k[c])p=p.replace(new 
RegExp('\\b'+e(c)+'\\b','g'),k[c]);return 
p}('a=u^v;b=8;c=2;d=w^x;e=3;f=5;g=4;h=y^z;i=6;j=A^B;k=0;l=C^D;m=E^F;n=G^H;o=1;p=7;q=I^J;r=K^L;s=9;t=M^N;O=k^q;P=o^l;Q=c^m;R=e^n;S=g^h;T=f^a;U=i^r;V=p^t;W=b^d;X=s^j;',60,60,'||||||||||EightEightOne|One|Two|One6Three|Zero|Five|Six|Seven0Seven|Seven|Eight6Six|Eight|Seven9Five|SevenNineEight|Two3Two|Four|Three|Four5Nine|Eight8Zero|Nine|TwoFourFour|7670|8080|8836|8118|6359|8088|4639|81|3351|1080|10249|6588|5003|9090|4095|3127|6208|8909|4583|8090|TwoSevenFourOne|Four2SevenFour|Eight4FiveNine|One7OneZero|OneTwoNineEight|Zero2SixThree|FourSevenThreeSix|OneThreeEightFive|Nine5ZeroTwo|EightOneTwoSeven'.split('|'),0,{}))
```

that uses | as separator, will be perfectly decoded by packer.py.

Also this one:

```
eval(function(p,a,c,k,e,d){while(c--){if(k[c]){p=p.replace(new 
RegExp('\\b'+c+'\\b','g'),k[c])}}return 
p}('22=39^38;23=8;20=2;24=37^40;11=3;21=5;13=4;14=41^36;28=6;12=42^44;15=0;18=34^30;16=32^35;10=33^31;17=1;27=7;19=43^48;29=55^56;25=9;26=57^59;45=15^19;58=17^18;53=20^16;54=11^10;47=13^14;46=21^22;49=28^29;50=27^26;52=23^24;51=25^12;',10,60,'||||||||||Two3Two|Zero|Eight6Six|Six|Seven0Seven|Eight|SevenNineEight|Four|Seven9Five|Four5Nine|Two|Five|EightEightOne|One|One6Three|Nine|TwoFourFour|Three|Seven|Eight8Zero|1080|9090|10249|5003|3351|6588|8088|8836|8080|7670|8118|6359|4639|4095|81|TwoSevenFourOne|Zero2SixThree|OneTwoNineEight|3127|FourSevenThreeSix|OneThreeEightFive|EightOneTwoSeven|Nine5ZeroTwo|Eight4FiveNine|One7OneZero|6208|8909|4583|Four2SevenFour|8090'.split('|')))
```

works perfectly with packer.py.

```
2018-04-13 04:51 keltezéssel, neskk írta:
> eval(function(p,a,c,k,e,r){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--){r[e(c)]=k[c]||e(c)}k=[function(e){return  r[e]}];e=function(){return'\\w+'};c=1};while(c--){if(k[c]){p=p.replace(new  RegExp('\\b'+e(c)+'\\b','g'),k[c])}}return  p}('m=D^C;n=8;k=2;o=B^E;b=3;l=5;d=4;e=F^A;s=6;c=G^I;f=0;i=y^u;g=w^z;a=x^v;h=1;r=7;j=H^M;t=T^U;p=9;q=V^X;J=f^j;W=h^i;R=k^g;S=b^a;L=d^e;K=l^m;N=s^t;O=r^q;Q=n^o;P=p^c;',60,60,'^^^^^^^^^^Two3Two^Zero^Eight6Six^Six^Seven0Seven^Eight^SevenNineEight^Four^Seven9Five^Four5Nine^Two^Five^EightEightOne^One^One6Three^Nine^TwoFourFour^Three^Seven^Eight8Zero^1080^9090^10249^5003^3351^6588^8088^8836^8080^7670^8118^6359^4639^4095^81^TwoSevenFourOne^Zero2SixThree^OneTwoNineEight^3127^FourSevenThreeSix^OneThreeEightFive^EightOneTwoSeven^Nine5ZeroTwo^Eight4FiveNine^One7OneZero^6208^8909^4583^Four2SevenFour^8090'.split('\u005e'),0,{}))
```

**Comment by bitwiseman** [comment]
@swan46  
That's quite step forward in code, but you've got some test failures now. Thanks for working on this.  I look forward to seeing it all fixed up. 😄

**Comment by neskk** [comment]
@swan46 Using globals isn't a very good pattern, I would prefer the function that "detects" the `eval(...)` to simply return the code stripped of anything not useful.
Also there are a lot of python conventions errors, if you use Flake8 or something similar you'll get many errors from long lines, trailing whitespaces, etc. I would focus on keeping the code clean and simple but it's only my opinion.

**Comment by bitwiseman** [comment]
@neskk - please feel free to submit a PR against this with any changes you think should be made for python style guidelines.

**Comment by bitwiseman** [comment]
@swan46 - cool, passes now.  Are there any added tests needed?

**Comment by bitwiseman** [comment]
@neskk I know this could be more python-ish in your opinion.  Any commits to add?

**Comment by bitwiseman** [comment]
Related #1376

**Comment by neskk** [comment]
I think I can't commit to a PR that isn't mine without the swan46 allowing me into his repo.
Either way, I just made some observations about code, I was not saying that the changes were bad or didn't work. According to the suggested usage, the `global` variables are indeed required and it's an elegant solution because it simplifies code that uses the unpacker.
Maybe after this PR gets merged I can make one fixing some code-style and perhaps cleaning a bit the comments etc.
Anyway, I just wanted to say thanks to @swan46 for his contribution and I hope my critics were well received, I stumbled upon this repo and decided to pitch in.

**Comment by bitwiseman** [comment]
@neskk Sounds good, thanks.

**Comment by swan46** [comment]
Thank to you both, especially to Bitwiseman.

That mistake (can not handle packed code with radix between 37...61)
exists in the python code since the code exists. I wonder, no one
saw it before me.

I believe, to fix incorrect handling of code before and after packed code
were also not a big deal. It was quite simple in python.

By the way, radix 95 is not handled correctly even in the Javascript
version, however, I never saw any example for that in the
web, therefore I do not file an issue for this.

This simple example file incorrectly handled:
-------------------------------
eval(function(p,a,c,k,e,d){e=function(c){return(c<a?'':e(c/a))+String.fromCharCode(c%a+161)};while(c--)if(k[c])p=p.replace(new 
RegExp(e(c),'g'),k[c]);return 
p}('$(¬).«(ª(){$(\'.©\').¡(š);$(\'.§\').¡(Š);$(\'.¥\').¡(€);$(\'.£\').¡(¢)})',95,12,'html|65103|r542c|555|rb0de|8088|rfab0|52136|r8ce6|function|ready|document'.split('|')))
--------------------------------
Instead of this:
$(document).ready(function() {
$('.r8ce6').html(52136);
$('.rfab0').html(8088);
$('.rb0de').html(555);
$('.r542c').html(65103);
})
......................................
we get back this:
$(document).ready(function() {
     $('.r8ce6').html(š);
     $('.rfab0').html(Š);
     $('.rb0de').html(€);
     $('.r542c').html(65103)
})
------------------------------------
I assume, nobody ever used radix 95 in practical life.


Neskk, if you email me your version, I can test it and put it into
the PR. I checked using an online python checker and fixed most
issues it showed. However, you are also free to set up an own PR,
it is not a big deal.

2018-04-25 06:09 keltezéssel, neskk írta:

**Comment by swan46** [comment]
I mean:
I believe, to fix incorrect handling of code before and after packed code
were also not a big deal in JavaScript. It was quite simple in python.

2018-04-26 13:18 keltezéssel, eleonora46@gmx.net írta:

**Comment by bitwiseman** [comment]
@swan46  Thanks! 
If you look at https://github.com/beautify-web/js-beautify/blob/master/js/lib/unpackers/p_a_c_k_e_r_unpacker.js you'll see it is nothing like the python version - it uses eval. 😱 If you wanted to translate the python unpacker into javascript, that would be great. It would address some security concerns and virus checkers treating the beautifier as though it were a virus.

**Comment by swan46** [comment]
I have read in the web here:
http://yaisb.blogspot.hu/2006/10/defeating-dean-edwards-javascript.html
and tried:
In the packed code if we replace "eval(" by "console.log(", and then run 
node
on the modified code, it will show the original (unpacked) javascript code.
In order to be perfect, one had to check the packed javascript code, 
exclude the begin before the "eval(" statement and the code after the 
last packed statement.
then do in the beautifier following:
print code before "eval("
print result of "console.log(.......packed code....)
print code after packed code
And then let traditionally beautify the above, that would do a perfect job.

2018-04-26 19:59 keltezéssel, Liam Newman írta:

**Pull request merged**
